// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/order_changed_service/gateway.go
//
// Generated by this command:
//
//	mockgen -source internal/service/order_changed_service/gateway.go -destination internal/service/order_changed_service/mocks/mock_gateway.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	order "course-go-avito-SitnikovArtem06/internal/gateway/order"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockorderGateway is a mock of orderGateway interface.
type MockorderGateway struct {
	ctrl     *gomock.Controller
	recorder *MockorderGatewayMockRecorder
	isgomock struct{}
}

// MockorderGatewayMockRecorder is the mock recorder for MockorderGateway.
type MockorderGatewayMockRecorder struct {
	mock *MockorderGateway
}

// NewMockorderGateway creates a new mock instance.
func NewMockorderGateway(ctrl *gomock.Controller) *MockorderGateway {
	mock := &MockorderGateway{ctrl: ctrl}
	mock.recorder = &MockorderGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderGateway) EXPECT() *MockorderGatewayMockRecorder {
	return m.recorder
}

// GetOrder mocks base method.
func (m *MockorderGateway) GetOrder(ctx context.Context, orderID string) (*order.OrderDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, orderID)
	ret0, _ := ret[0].(*order.OrderDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockorderGatewayMockRecorder) GetOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockorderGateway)(nil).GetOrder), ctx, orderID)
}
