// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/order_status_factory/order_status_factory.go
//
// Generated by this command:
//
//	mockgen -source internal/service/order_status_factory/order_status_factory.go -destination internal/service/order_changed_service/mocks/mock_status_factory.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	order_status_factory "course-go-avito-SitnikovArtem06/internal/service/order_status_factory"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderStatus is a mock of OrderStatus interface.
type MockOrderStatus struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStatusMockRecorder
	isgomock struct{}
}

// MockOrderStatusMockRecorder is the mock recorder for MockOrderStatus.
type MockOrderStatusMockRecorder struct {
	mock *MockOrderStatus
}

// NewMockOrderStatus creates a new mock instance.
func NewMockOrderStatus(ctrl *gomock.Controller) *MockOrderStatus {
	mock := &MockOrderStatus{ctrl: ctrl}
	mock.recorder = &MockOrderStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStatus) EXPECT() *MockOrderStatusMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockOrderStatus) Do(ctx context.Context, orderId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, orderId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockOrderStatusMockRecorder) Do(ctx, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockOrderStatus)(nil).Do), ctx, orderId)
}

// MockOrderStatusFactory is a mock of OrderStatusFactory interface.
type MockOrderStatusFactory struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStatusFactoryMockRecorder
	isgomock struct{}
}

// MockOrderStatusFactoryMockRecorder is the mock recorder for MockOrderStatusFactory.
type MockOrderStatusFactoryMockRecorder struct {
	mock *MockOrderStatusFactory
}

// NewMockOrderStatusFactory creates a new mock instance.
func NewMockOrderStatusFactory(ctrl *gomock.Controller) *MockOrderStatusFactory {
	mock := &MockOrderStatusFactory{ctrl: ctrl}
	mock.recorder = &MockOrderStatusFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStatusFactory) EXPECT() *MockOrderStatusFactoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockOrderStatusFactory) Get(status string) order_status_factory.OrderStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", status)
	ret0, _ := ret[0].(order_status_factory.OrderStatus)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockOrderStatusFactoryMockRecorder) Get(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrderStatusFactory)(nil).Get), status)
}
