// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handlers/courier_handler/service_contract.go
//
// Generated by this command:
//
//	mockgen -source=internal/handlers/courier_handler/service_contract.go -destination=internal/handlers/courier_handler/mocks/courier_service_mock.go -package=courier_handler
//

// Package courier_handler is a generated GoMock package.
package courier_handler

import (
	context "context"
	model "course-go-avito-SitnikovArtem06/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockcourierService is a mock of courierService interface.
type MockcourierService struct {
	ctrl     *gomock.Controller
	recorder *MockcourierServiceMockRecorder
	isgomock struct{}
}

// MockcourierServiceMockRecorder is the mock recorder for MockcourierService.
type MockcourierServiceMockRecorder struct {
	mock *MockcourierService
}

// NewMockcourierService creates a new mock instance.
func NewMockcourierService(ctrl *gomock.Controller) *MockcourierService {
	mock := &MockcourierService{ctrl: ctrl}
	mock.recorder = &MockcourierServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierService) EXPECT() *MockcourierServiceMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockcourierService) CreateCourier(ctx context.Context, c *model.CreateCourierRequest) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", ctx, c)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockcourierServiceMockRecorder) CreateCourier(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockcourierService)(nil).CreateCourier), ctx, c)
}

// GetAllCouriers mocks base method.
func (m *MockcourierService) GetAllCouriers(ctx context.Context) ([]model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCouriers", ctx)
	ret0, _ := ret[0].([]model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCouriers indicates an expected call of GetAllCouriers.
func (mr *MockcourierServiceMockRecorder) GetAllCouriers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCouriers", reflect.TypeOf((*MockcourierService)(nil).GetAllCouriers), ctx)
}

// GetCourierById mocks base method.
func (m *MockcourierService) GetCourierById(ctx context.Context, id int64) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierById", ctx, id)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierById indicates an expected call of GetCourierById.
func (mr *MockcourierServiceMockRecorder) GetCourierById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierById", reflect.TypeOf((*MockcourierService)(nil).GetCourierById), ctx, id)
}

// UpdateCourier mocks base method.
func (m *MockcourierService) UpdateCourier(ctx context.Context, req *model.UpdateCourierRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockcourierServiceMockRecorder) UpdateCourier(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockcourierService)(nil).UpdateCourier), ctx, req)
}
