// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/transport_factory/transport_factory.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/transport_factory/transport_factory.go -destination=internal/service/mocks/mock_transport_factory.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "course-go-avito-SitnikovArtem06/internal/model"
	transport_factory "course-go-avito-SitnikovArtem06/internal/service/transport_factory"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTransport is a mock of Transport interface.
type MockTransport struct {
	ctrl     *gomock.Controller
	recorder *MockTransportMockRecorder
	isgomock struct{}
}

// MockTransportMockRecorder is the mock recorder for MockTransport.
type MockTransportMockRecorder struct {
	mock *MockTransport
}

// NewMockTransport creates a new mock instance.
func NewMockTransport(ctrl *gomock.Controller) *MockTransport {
	mock := &MockTransport{ctrl: ctrl}
	mock.recorder = &MockTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransport) EXPECT() *MockTransportMockRecorder {
	return m.recorder
}

// Deadline mocks base method.
func (m *MockTransport) Deadline() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deadline")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Deadline indicates an expected call of Deadline.
func (mr *MockTransportMockRecorder) Deadline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deadline", reflect.TypeOf((*MockTransport)(nil).Deadline))
}

// MockTransportFactory is a mock of TransportFactory interface.
type MockTransportFactory struct {
	ctrl     *gomock.Controller
	recorder *MockTransportFactoryMockRecorder
	isgomock struct{}
}

// MockTransportFactoryMockRecorder is the mock recorder for MockTransportFactory.
type MockTransportFactoryMockRecorder struct {
	mock *MockTransportFactory
}

// NewMockTransportFactory creates a new mock instance.
func NewMockTransportFactory(ctrl *gomock.Controller) *MockTransportFactory {
	mock := &MockTransportFactory{ctrl: ctrl}
	mock.recorder = &MockTransportFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransportFactory) EXPECT() *MockTransportFactoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTransportFactory) Get(transportType model.TransportType) transport_factory.Transport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", transportType)
	ret0, _ := ret[0].(transport_factory.Transport)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockTransportFactoryMockRecorder) Get(transportType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTransportFactory)(nil).Get), transportType)
}
