// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/courier_repository/repo_contract.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/courier_repository/repo_contract.go -destination=internal/service/mocks/mock_courier_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "course-go-avito-SitnikovArtem06/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCourierRepository is a mock of CourierRepository interface.
type MockCourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourierRepositoryMockRecorder
	isgomock struct{}
}

// MockCourierRepositoryMockRecorder is the mock recorder for MockCourierRepository.
type MockCourierRepositoryMockRecorder struct {
	mock *MockCourierRepository
}

// NewMockCourierRepository creates a new mock instance.
func NewMockCourierRepository(ctrl *gomock.Controller) *MockCourierRepository {
	mock := &MockCourierRepository{ctrl: ctrl}
	mock.recorder = &MockCourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierRepository) EXPECT() *MockCourierRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCourierRepository) Create(ctx context.Context, courier *model.CourierDB) (*model.CourierDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, courier)
	ret0, _ := ret[0].(*model.CourierDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCourierRepositoryMockRecorder) Create(ctx, courier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCourierRepository)(nil).Create), ctx, courier)
}

// Get mocks base method.
func (m *MockCourierRepository) Get(ctx context.Context, id int64) (*model.CourierDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.CourierDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCourierRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCourierRepository)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockCourierRepository) GetAll(ctx context.Context) ([]model.CourierDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]model.CourierDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCourierRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCourierRepository)(nil).GetAll), ctx)
}

// GetAvailableCouriers mocks base method.
func (m *MockCourierRepository) GetAvailableCouriers(ctx context.Context) ([]model.CourierDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableCouriers", ctx)
	ret0, _ := ret[0].([]model.CourierDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableCouriers indicates an expected call of GetAvailableCouriers.
func (mr *MockCourierRepositoryMockRecorder) GetAvailableCouriers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableCouriers", reflect.TypeOf((*MockCourierRepository)(nil).GetAvailableCouriers), ctx)
}

// Update mocks base method.
func (m *MockCourierRepository) Update(ctx context.Context, req *model.UpdateCourierRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCourierRepositoryMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCourierRepository)(nil).Update), ctx, req)
}

// UpdateAllExpiredCourier mocks base method.
func (m *MockCourierRepository) UpdateAllExpiredCourier(ctx context.Context, ids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAllExpiredCourier", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAllExpiredCourier indicates an expected call of UpdateAllExpiredCourier.
func (mr *MockCourierRepositoryMockRecorder) UpdateAllExpiredCourier(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAllExpiredCourier", reflect.TypeOf((*MockCourierRepository)(nil).UpdateAllExpiredCourier), ctx, ids)
}
