// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/delivery_repository/repo_contract.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/delivery_repository/repo_contract.go -destination=internal/service/mocks/mock_delivery_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "course-go-avito-SitnikovArtem06/internal/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDeliveryRepository is a mock of DeliveryRepository interface.
type MockDeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRepositoryMockRecorder
	isgomock struct{}
}

// MockDeliveryRepositoryMockRecorder is the mock recorder for MockDeliveryRepository.
type MockDeliveryRepositoryMockRecorder struct {
	mock *MockDeliveryRepository
}

// NewMockDeliveryRepository creates a new mock instance.
func NewMockDeliveryRepository(ctrl *gomock.Controller) *MockDeliveryRepository {
	mock := &MockDeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockDeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRepository) EXPECT() *MockDeliveryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeliveryRepository) Create(ctx context.Context, orderId string, courierId int64, deadline time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orderId, courierId, deadline)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeliveryRepositoryMockRecorder) Create(ctx, orderId, courierId, deadline any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeliveryRepository)(nil).Create), ctx, orderId, courierId, deadline)
}

// Delete mocks base method.
func (m *MockDeliveryRepository) Delete(ctx context.Context, orderId string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orderId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDeliveryRepositoryMockRecorder) Delete(ctx, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeliveryRepository)(nil).Delete), ctx, orderId)
}

// GetByOrderId mocks base method.
func (m *MockDeliveryRepository) GetByOrderId(ctx context.Context, orderID string) (*model.DeliveryDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderId", ctx, orderID)
	ret0, _ := ret[0].(*model.DeliveryDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderId indicates an expected call of GetByOrderId.
func (mr *MockDeliveryRepositoryMockRecorder) GetByOrderId(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderId", reflect.TypeOf((*MockDeliveryRepository)(nil).GetByOrderId), ctx, orderID)
}

// GetCourierWithMinimumOrder mocks base method.
func (m *MockDeliveryRepository) GetCourierWithMinimumOrder(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierWithMinimumOrder", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierWithMinimumOrder indicates an expected call of GetCourierWithMinimumOrder.
func (mr *MockDeliveryRepositoryMockRecorder) GetCourierWithMinimumOrder(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierWithMinimumOrder", reflect.TypeOf((*MockDeliveryRepository)(nil).GetCourierWithMinimumOrder), ctx)
}

// GetExpiredOrders mocks base method.
func (m *MockDeliveryRepository) GetExpiredOrders(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiredOrders", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpiredOrders indicates an expected call of GetExpiredOrders.
func (mr *MockDeliveryRepositoryMockRecorder) GetExpiredOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiredOrders", reflect.TypeOf((*MockDeliveryRepository)(nil).GetExpiredOrders), ctx)
}
