// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handlers/assign_handler/assign_service_contract.go
//
// Generated by this command:
//
//	mockgen -source=internal/handlers/assign_handler/assign_service_contract.go -destination=internal/handlers/assign_handler/mocks/assign_service_mock.go -package=assign_handler
//

// Package assign_handler is a generated GoMock package.
package assign_handler

import (
	context "context"
	model "course-go-avito-SitnikovArtem06/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockassignService is a mock of assignService interface.
type MockassignService struct {
	ctrl     *gomock.Controller
	recorder *MockassignServiceMockRecorder
	isgomock struct{}
}

// MockassignServiceMockRecorder is the mock recorder for MockassignService.
type MockassignServiceMockRecorder struct {
	mock *MockassignService
}

// NewMockassignService creates a new mock instance.
func NewMockassignService(ctrl *gomock.Controller) *MockassignService {
	mock := &MockassignService{ctrl: ctrl}
	mock.recorder = &MockassignServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockassignService) EXPECT() *MockassignServiceMockRecorder {
	return m.recorder
}

// AssignCourier mocks base method.
func (m *MockassignService) AssignCourier(ctx context.Context, orderId string) (*model.AssignCourier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCourier", ctx, orderId)
	ret0, _ := ret[0].(*model.AssignCourier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignCourier indicates an expected call of AssignCourier.
func (mr *MockassignServiceMockRecorder) AssignCourier(ctx, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCourier", reflect.TypeOf((*MockassignService)(nil).AssignCourier), ctx, orderId)
}

// UnassignCourier mocks base method.
func (m *MockassignService) UnassignCourier(ctx context.Context, orderId string) (*model.UnassignCourier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignCourier", ctx, orderId)
	ret0, _ := ret[0].(*model.UnassignCourier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignCourier indicates an expected call of UnassignCourier.
func (mr *MockassignServiceMockRecorder) UnassignCourier(ctx, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignCourier", reflect.TypeOf((*MockassignService)(nil).UnassignCourier), ctx, orderId)
}
