// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/order_monitor_service/assign_contract.go
//
// Generated by this command:
//
//	mockgen -source internal/service/order_monitor_service/assign_contract.go -destination internal/service/order_monitor_service/mocks/mock_assign.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "course-go-avito-SitnikovArtem06/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockassign is a mock of assign interface.
type Mockassign struct {
	ctrl     *gomock.Controller
	recorder *MockassignMockRecorder
	isgomock struct{}
}

// MockassignMockRecorder is the mock recorder for Mockassign.
type MockassignMockRecorder struct {
	mock *Mockassign
}

// NewMockassign creates a new mock instance.
func NewMockassign(ctrl *gomock.Controller) *Mockassign {
	mock := &Mockassign{ctrl: ctrl}
	mock.recorder = &MockassignMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockassign) EXPECT() *MockassignMockRecorder {
	return m.recorder
}

// AssignCourier mocks base method.
func (m *Mockassign) AssignCourier(ctx context.Context, orderId string) (*model.AssignCourier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCourier", ctx, orderId)
	ret0, _ := ret[0].(*model.AssignCourier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignCourier indicates an expected call of AssignCourier.
func (mr *MockassignMockRecorder) AssignCourier(ctx, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCourier", reflect.TypeOf((*Mockassign)(nil).AssignCourier), ctx, orderId)
}
