// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/order_monitor_service/gateway.go
//
// Generated by this command:
//
//	mockgen -source internal/service/order_monitor_service/gateway.go -destination internal/service/order_monitor_service/mocks/mock_gateway.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "course-go-avito-SitnikovArtem06/internal/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// Mockgateway is a mock of gateway interface.
type Mockgateway struct {
	ctrl     *gomock.Controller
	recorder *MockgatewayMockRecorder
	isgomock struct{}
}

// MockgatewayMockRecorder is the mock recorder for Mockgateway.
type MockgatewayMockRecorder struct {
	mock *Mockgateway
}

// NewMockgateway creates a new mock instance.
func NewMockgateway(ctrl *gomock.Controller) *Mockgateway {
	mock := &Mockgateway{ctrl: ctrl}
	mock.recorder = &MockgatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockgateway) EXPECT() *MockgatewayMockRecorder {
	return m.recorder
}

// GetNewOrders mocks base method.
func (m *Mockgateway) GetNewOrders(ctx context.Context, from time.Time) (*model.OrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewOrders", ctx, from)
	ret0, _ := ret[0].(*model.OrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNewOrders indicates an expected call of GetNewOrders.
func (mr *MockgatewayMockRecorder) GetNewOrders(ctx, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewOrders", reflect.TypeOf((*Mockgateway)(nil).GetNewOrders), ctx, from)
}
